Q1 Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values.

In [1]:
from google.colab import files

uploaded = files.upload()

Saving employee_productivity_dataset.csv to employee_productivity_dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv("employee_productivity_dataset.csv")
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

Q1 Missing Values

In [3]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
df["Hours_Worked_Per_Week"].fillna(df["Hours_Worked_Per_Week"].median(), inplace=True)
df["Performance_Score"].fillna(df["Performance_Score"].mean(), inplace=True)

df.head()

/tmp/ipykernel_3837/1701585339.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_3837/1701585339.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)
/tmp/ipykernel_3837/1701585339.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Hours_Worked_Per_Week"].fillna(df["Hours_Worked_Per_Week"].median(), inplace=True)
/tmp/ipykernel_3837/1701585339.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Performance_Score"].fillna(df["Performance_Score"].mean(), inplace=True)

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune

Q2 Label Encoding

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Department"] = le.fit_transform(df["Department"])

df[["Gender","Department"]].head()

   Gender  Department
0       1           2
1       0           1
2       1           0
3       0           2
4       1           3

Q3 One Hot Encoding

In [5]:
df = pd.get_dummies(df, columns=["Work_Mode","Location"])

df.head()

,Employee_ID,Name,Department,Age,Gender,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune
0,E001,Amit Sharma,2,25.0,1,15-01-2021,40.0,5,4.5000,50000.000000,False,False,True,False,False,False,True
1,E002,Riya Patel,1,30.0,0,15-02-2020,38.0,4,4.0000,45000.000000,True,False,False,False,False,True,False
2,E003,John Mathew,0,29.0,1,10-03-2022,45.0,6,4.3125,60000.000000,False,True,False,True,False,False,False
3,E004,Sneha Joshi,2,28.0,0,22-04-2021,41.0,5,4.2000,52000.000000,False,False,True,False,True,False,False
4,E005,Arjun Verma,3,35.0,1,18-05-2020,50.0,7,4.8000,50666.666667,True,False,False,False,False,False,True

In [6]:
print(df.shape)

(250, 17)

Q4 Normalization

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[["Salary","Hours_Worked_Per_Week"]] = scaler.fit_transform(
    df[["Salary","Hours_Worked_Per_Week"]]
)

df[["Salary","Hours_Worked_Per_Week"]].head()

     Salary  Hours_Worked_Per_Week
0  0.347826               0.285714
1  0.130435               0.142857
2  0.782609               0.642857
3  0.434783               0.357143
4  0.376812               1.000000

Q5 Standardization

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["Age","Projects_Completed"]] = scaler.fit_transform(
    df[["Age","Projects_Completed"]]
)

df[["Age","Projects_Completed"]].head()

        Age  Projects_Completed
0 -1.172018           -0.211604
1  0.000000           -0.916949
2 -0.234404            0.493742
3 -0.468807           -0.211604
4  1.172018            1.199088

Q6 Compare Scaling

In [9]:
df2 = pd.read_csv("employee_productivity_dataset.csv")

df2["Salary"].fillna(df2["Salary"].mean(), inplace=True)

/tmp/ipykernel_3837/446690006.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["Salary"].fillna(df2["Salary"].mean(), inplace=True)

In [10]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

minmax = MinMaxScaler()
standard = StandardScaler()

df2["MinMax"] = minmax.fit_transform(df2[["Salary"]])

df2["Standard"] = standard.fit_transform(df2[["Salary"]])

df2[["Salary","MinMax","Standard"]].head()

         Salary    MinMax  Standard
0  50000.000000  0.347826 -0.097451
1  45000.000000  0.130435 -0.828333
2  60000.000000  0.782609  1.364312
3  52000.000000  0.434783  0.194902
4  50666.666667  0.376812  0.000000

Q7 Pipeline

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [13]:
cat_cols = ["Department","Gender","Work_Mode","Location"]

num_cols = ["Age","Salary","Hours_Worked_Per_Week",
            "Projects_Completed","Performance_Score"]

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(), cat_cols),
    ("num", StandardScaler(), num_cols)
])

pipeline = Pipeline([
    ("preprocessor", preprocessor)
])

print("Pipeline Created")

Pipeline Created

Q8 Apply Pipeline

In [14]:
X = df2[cat_cols + num_cols]

result = pipeline.fit_transform(X)

print(result)
print(result.shape)

[[ 0.          0.          1.         ... -0.41039134 -0.21160368
   0.61288338]
 [ 0.          1.          0.         ... -0.82078268 -0.9169493
  -1.02147231]
 [ 1.          0.          0.         ...  0.61558701  0.49374193
          nan]
 ...
 [ 0.          0.          0.         ...  0.          0.49374193
  -0.04085889]
 [ 0.          0.          1.         ...         nan -0.21160368
  -0.69460117]
 [ 0.          1.          0.         ... -1.02597835 -0.9169493
          nan]]
(250, 18)

Q9. Conceptual Question

Why is scaling important in Python?

Answer: Scaling is important because different columns have different ranges. Scaling brings all values to a similar range, improves model accuracy and speeds up training.

Q10. Why do we convert categorical data into numerical form?

Answer:
Machine Learning algorithms cannot understand text values directly. Therefore categorical values like Male/Female or HR/IT are converted into numerical form using encoding techniques.